name: CI/CD for ML Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: random_forest_beer_model.pkl

      - name: Debug before committing logs
        run: |
          echo "Debugging log changes before commit:"
          git status
          ls -l logs/

      - name: Commit and push updated logs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "elqadyahmed@gmail.com"
          git config --global user.name "AHMADELQADY"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/AHMADELQADY/beer-match-project.git
          git stash || echo "No changes to stash"
          git pull origin main --rebase || echo "Rebase failed"
          git stash pop || echo "No stash to apply"
          git add logs/*.txt
          git commit -m "Updated logs after CI/CD execution" || echo "No changes to commit"
          git push origin main || echo "Push failed, please check permissions"

      - name: Verify after push
        run: |
          echo "Verifying state after push:"
          git status
          ls -l logs/