name: CI/CD for ML Model

on:
  push:
    branches:
      - main  # Esegue il workflow quando si aggiorna la branch principale
  workflow_dispatch:  # Permette di avviare il workflow manualmente da GitHub

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Train model
      - name: Train model
        run: |
          python train.py

      # Step 5: Upload trained model
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: random_forest_beer_model.pkl

      # Step 6: Commit and push updated logs
      - name: Commit and push updated logs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "elqadyahmed@gmail.com"
          git config --global user.name "AHMADELQADY"
          git add logs/*.txt
          git commit -m "Updated logs after CI/CD execution"
          git push origin main

      # Step 7: Deployment step (placeholder)
      - name: Deploy model
        run: |
          echo "Deployment logic goes here. Example: Docker, Streamlit, or FastAPI."